2021-05-25 10:09:03,989 - F:\autotest\scripts1\utils\log.py[line:89] - ERROR: error333
2021-05-25 10:13:52,250 - F:\autotest\scripts1\utils\log.py[line:89] - ERROR: error333
