2021-01-07 16:18:54,584 - F:/autotest/scripts1/utils/log.py[line:87] - ERROR: error333
2021-01-07 16:19:24,271 - F:/autotest/scripts1/utils/log.py[line:87] - ERROR: error333
2021-01-07 16:19:43,187 - F:/autotest/scripts1/utils/log.py[line:87] - ERROR: error333
